project:
  type: book
  output-dir: docs

book:
  title: "Django y React 2024"
  author: "Diego Saavedra"
  output-file: "curso_django_and_react_2024"  
  date: today
  date-format: medium
  favicon: logo.png
  description: Curso de Django y React 2024
  keyword: Python, Dajngo, JavaScript, React
  url: https://github.com/statick88/Course_of_django_and_react
  page-navigation: true
  sidebar: 
    logo: logo.png
    search: true
    collapse-level: 1

  repo-subdir: book
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  image: logo.png

  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
        
  chapters:
    - index.qmd
    - part: "Unidad 1: Introducción a Python"
      chapters: 
        - unidades/unidad1/1_git_y_github.qmd
        - unidades/unidad1/2_github_classroom.qmd
        - unidades/unidad1/3_docker.qmd

    - part: "Unidad 2: Python Básico"
      chapters: 
        - unidades/unidad2/1_introduccion.qmd
        - unidades/unidad2/2_variable_y_control_de_flujo.qmd

    - part: "Unidad 3: Python Intermedio"
      chapters: 
        - unidades/unidad3/3_listas_tuplas.qmd
        - unidades/unidad3/4_conjuntos_diccionarios.qmd

    - part: "Unidad 4: Python Avanzado"
      chapters: 
        - unidades/unidad4/5_programacion_oo.qmd
        - unidades/unidad4/6_modulos.qmd
        - unidades/unidad4/7_pypi.qmd
        - unidades/unidad4/8_publicar_pypi.qmd
        - unidades/unidad4/project001.qmd

    - part: "Unidad 5: Django"
      chapters: 
        - unidades/unidad5/1_django_fundamentos.qmd
        - unidades/unidad5/2_configuracion_inicial.qmd
        - unidades/unidad5/3_estructura_archivos_directorios.qmd
        - unidades/unidad5/4_modelos_vistas_plantillas.qmd
        - unidades/unidad5/5_drf.qmd
        - unidades/unidad5/6_base_de_datos.qmd
        - unidades/unidad5/7_testing.qmd
        - unidades/unidad5/8_correccion_test.qmd

    - part: "Unidad 6: Frontend"
      chapters:
        - unidades/unidad6/1_introduccion_frontend.qmd
        - unidades/unidad6/2_introduccion_css.qmd
        - unidades/unidad6/3_introduccion_javascript.qmd
        - unidades/unidad6/4_introduccion_node.qmd
        - unidades/unidad6/5_introduccion_react.qmd
        - unidades/unidad6/6_primeros_pasos_con_react.qmd
        - unidades/unidad6/7_fetch_con_react.qmd
        - unidades/unidad6/8_fetch_con_react_tiempo.qmd
        - unidades/unidad6/9_crud_react.qmd

    - part: "Ejercicios"
      chapters: 
        - unidades/ejercicios/lab1.qmd
        - unidades/ejercicios/ejercicios_git_github-000.qmd
        - unidades/ejercicios/ejercicios_python-001.qmd
        - unidades/ejercicios/ejercicios_python-002.qmd
        - unidades/ejercicios/ejercicios_python-003.qmd
        - unidades/ejercicios/ejercicios_python-004.qmd

bibliography: references.bib
biblio-style: "apalike"

format:
  html:
    number-sections: false
    theme: 
      dark:  solar #slate, darkly, solar, superhero, vapor
      # light: cosmo
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true
    css: css/styles.css

  pdf:
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 35mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry: 
      - top=35mm
      - bottom=30mm
      - right=30mm
      - left=30mm
  epub: 
    belongs-to-collection: "Curso de Django y React 2024"
    group-position: 0
    creator: "Lcdo. Diego Saavedra Mgtr."
    rights: "© Statick | 2024"
    fig-responsive: true
    number-sections: true

filters:
  - naquiz